server:
  port: 9090

spotify:
  clientId: 6d1aba85011246b79d00fda8c9902ee3
  secret:
    filename: spotify-secret.txt
  uri:
    redirect: http://localhost:9090/api/v1/auth/token
    search:
      track: https://api.spotify.com/v1/search?q={query}&type=track&limit=50
  combinator:
    words:
      limit: 6
    cleanup:
      regex: "[! .,-]"
