server:
  port: 9090
spotify:
  clientId: 6d1aba85011246b79d00fda8c9902ee3
  secret:
    filename: spotify-secret
  uri:
    redirect: http://localhost:9090/api/v1/auth/token
  retry_wait_time_ms: 5000
  combinator:
    words:
      limit: 6
    cleanup:
      regex: "[! .,-]"
